simParams:
  imageWidth: 320
  imageHeight: 240
  imageLaneWidth: 224
  imageLaneHeight: 224
  incrementBBoxX: 7
  incrementBBoxY: 10
  textBBox: 5
  firstRedMask: [0, 170, 170, 10, 255, 255]
  secondRedMask: [170, 170, 170, 180, 255, 255]
  greenMask: [155, 199, 209, 133, 255, 255]
  trafficLightProb: 0.8
  stopSignProb: 0.97
  personProb: 0.8
  titleWidth: 200
  buttonWidth: 75
  stopButtonWidth: 15
  stopButtonHeight: 15
  robotName: "autonomous_vehicle"
  actorName: "actor"
  modelPath: "/home/alvaro/github/tfg-amariscal/models/road_following_model_sim.pth"
  appMinWidth: 910
  appMinHeight: 512
  turnVel: 0.75
  straightVel: 2
  startPoseX: -10.0
  startPoseY: 45.0
  startPoseZ: 4.0
  startOrientationZ: 0.7
  startOrientationW: 0.7
  deleteActorPoseX: 0.0
  deleteActorPoseY: 0.0
  deleteActorPoseZ: -100.0
  stopTime: 5
  timeBetweenStop: 20
  thirteenthState: 153.5
  twelfthState: [123, 0.0]
  eleventhState: 121
  tenthState: [116, -0.85]
  ninthState: 115.5
  eighthState: [77, -0.7]
  seventhState: 74
  sixthState: [71, 0.4]
  fifthState: 69
  fourthState: [42, 0.02]
  thirdState: 40
  secondState: [34, 0.4]
  firstState: 33
